# Generated by Django 4.0.5 on 2022-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='historia',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='idea',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
