# Generated by Django 4.0.5 on 2022-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoiar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiar',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apoiar',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
    ]
